"""
Constants for the 2D testbed application.
"""

import pygame

# Display settings
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 1200
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Camera settings
START_CAM_RADIUS = 200
START_CAM_ANGLE = 0
MIN_CAM_RADIUS = 50
MAX_CAM_RADIUS = 1000
CAMERA_MOVE_SPEED = 2
CAMERA_ROTATION_SPEED = 1

# Visual settings
DOT_RADIUS = 5
OBSERVATION_DOT_RADIUS = 3
MIN_RECTANGLE_SIZE = 5
FONT_SIZE = 36

# Input settings
MOUSE_RIGHT_BUTTON = 3

# Keys
KEY_MOVE_FORWARD = pygame.K_UP
KEY_MOVE_BACKWARD = pygame.K_DOWN
KEY_ROTATE_LEFT = pygame.K_LEFT
KEY_ROTATE_RIGHT = pygame.K_RIGHT
KEY_INCREMENT_RUN = pygame.K_SPACE
KEY_QUIT = pygame.K_ESCAPE